from collections.abc import Mapping, Sequence
from enum import StrEnum
from typing import Final, Literal

SDK_VERSION: Final[str]
GENERATOR_PROTOCOL: Final[int]
PYTHON_ABI: Final[str]

type JsonScalar = None | bool | int | float | str
type JsonValue = JsonScalar | tuple[JsonValue, ...] | Mapping[str, JsonValue]

class GeneratorSdkError(RuntimeError): ...
class InputAliasError(GeneratorSdkError): ...
class InputFormatError(GeneratorSdkError): ...
class InputDecodeError(GeneratorSdkError): ...
class BindingValidationError(GeneratorSdkError): ...
class DuplicateBindingError(GeneratorSdkError): ...
class ContextSealedError(GeneratorSdkError): ...

class InputFormat(StrEnum):
    BYTES = "bytes"
    UTF8 = "utf8"
    JSON = "json"

class ValueSpec:
    kind: str

NONE: Final[ValueSpec]
BOOL: Final[ValueSpec]
INT: Final[ValueSpec]
FLOAT: Final[ValueSpec]
STR: Final[ValueSpec]
BYTES: Final[ValueSpec]

def list_of(item: ValueSpec, /) -> ValueSpec: ...
def tuple_of(*items: ValueSpec, variadic: bool = False) -> ValueSpec: ...
def dict_of(key: ValueSpec, value: ValueSpec, /) -> ValueSpec: ...
def set_of(item: ValueSpec, /) -> ValueSpec: ...
def frozenset_of(item: ValueSpec, /) -> ValueSpec: ...
def optional(item: ValueSpec, /) -> ValueSpec: ...
def union_of(*items: ValueSpec) -> ValueSpec: ...
def literal(*values: None | bool | int | float | str | bytes) -> ValueSpec: ...
def enum_of(id: str, members: Mapping[str, None | bool | int | str], /) -> ValueSpec: ...
def record_of(id: str, fields: Sequence[ParameterSpec], /) -> ValueSpec: ...

class ParameterSpec:
    name: str
    value: ValueSpec
    required: bool
    def __init__(self, name: str, value: ValueSpec, /, *, required: bool = True, default: object = ...) -> None: ...

class BindingSpec:
    """Opaque binding proposal; only a generated BindingFactory constructs it."""

class BindingFactory:
    template_id: str
    parameters: tuple[ParameterSpec, ...]
    def __init__(self, template_id: str, parameters: Sequence[ParameterSpec], /) -> None: ...
    def __call__(self, *, id: str, **arguments: object) -> BindingSpec: ...

class GenerationContext:
    def bytes(self, name: str) -> bytes: ...
    def text(self, name: str) -> str: ...
    def json(self, name: str) -> JsonValue: ...
    def emit(self, binding: BindingSpec) -> None: ...

__all__: list[str]
