import builtins
from collections.abc import AsyncIterator, Awaitable, Callable, Generator, Iterator, Sequence
from contextlib import AbstractAsyncContextManager, AbstractContextManager
from datetime import datetime, timedelta
from enum import StrEnum
from typing import Any, Final, Literal, LiteralString, Protocol, Self, overload

SDK_VERSION: Final[str]
ENGINE_API: Final[int]
PYTHON_ABI: Final[str]

type Identity[T] = T
type Public[T] = T
type Internal[T] = T
type Sensitive[T] = T
type Secret[T] = T
type StableId = str
type CanonicalKey = None | bool | int | str | builtins.bytes | tuple[CanonicalKey, ...]
type PatternEncoding = Literal["utf-8", "utf-16-le", "utf-16-be", "ascii", "latin-1"]
type PatternCase = Literal["sensitive", "ascii_insensitive"]

class StaticIntrinsicError(RuntimeError): ...

class Model: ...
class WireRecord: ...
class EventRecord(WireRecord): ...
class StateRecord(WireRecord): ...

def provider_fact(
    *,
    route: LiteralString,
    cache: Literal["none", "evaluation", "subject_generation"] = "evaluation",
    cost: Literal["low", "medium", "high"] = "medium",
) -> Any: ...
def wire_field(*, id: int, default: Any = ...) -> Any: ...

class _TypeDecorator(Protocol):
    def __call__[T](self, target: type[T], /) -> type[T]: ...

def schema(id: LiteralString) -> _TypeDecorator: ...

class _EntrypointDecorator(Protocol):
    @overload
    def __call__[**P](self, target: Callable[P, bool], /) -> Callable[P, bool]: ...
    @overload
    def __call__[**P](self, target: Callable[P, Awaitable[bool]], /) -> Callable[P, Awaitable[bool]]: ...

def rule(
    id: LiteralString,
    *,
    budget: LiteralString | None = None,
    trace_policy: LiteralString | None = None,
) -> _EntrypointDecorator: ...
def rule_template(
    id: LiteralString,
    *,
    budget: LiteralString | None = None,
    trace_policy: LiteralString | None = None,
) -> _EntrypointDecorator: ...
def correlation(
    id: LiteralString,
    *,
    group_by: Callable[[Any], CanonicalKey] | None = None,
    order_by: Literal["ingest_time", "event_time"] = "ingest_time",
    allowed_lateness: timedelta | None = None,
    budget: LiteralString | None = None,
    trace_policy: LiteralString | None = None,
) -> _EntrypointDecorator: ...
def correlation_template(
    id: LiteralString,
    *,
    group_by: Callable[[Any], CanonicalKey] | None = None,
    order_by: Literal["ingest_time", "event_time"] = "ingest_time",
    allowed_lateness: timedelta | None = None,
    budget: LiteralString | None = None,
    trace_policy: LiteralString | None = None,
) -> _EntrypointDecorator: ...

class BoundEntrypoint:
    id: str
    def __call__(self, *args: Any, **kwargs: Any) -> bool: ...

def bind(template: Callable[..., bool] | Callable[..., Awaitable[bool]], /, *, id: LiteralString, **arguments: Any) -> BoundEntrypoint: ...

class SubjectKey[T]:
    peer_id: str
    scope_schema_id: str
    identity: tuple[CanonicalKey, ...]
    parent: SubjectKey[Any] | None

class FactError(RuntimeError): ...
class FactNotFound(FactError): ...
class FactUnsupported(FactError): ...
class FactAccessDenied(FactError): ...
class FactTimedOut(FactError): ...
class FactUnavailable(FactError): ...
class FactCanceled(FactError): ...
class FactMalformed(FactError): ...
class FactProtocolViolation(FactError): ...
class BoundaryValidationError(RuntimeError): ...
class DataPolicyViolation(RuntimeError): ...
class ScanResultLimitExceeded(RuntimeError): ...

class Pattern:
    id: str

class Match:
    pattern_id: str
    subject: SubjectKey[Any]
    offset: int
    absolute_address: int | None
    length: int
    permissions: frozenset[Literal["read", "write", "execute"]]
    before: builtins.bytes | None
    matched: builtins.bytes | None
    after: builtins.bytes | None

class MatchSet(Sequence[Match]):
    @overload
    def __getitem__(self, index: int, /) -> Match: ...
    @overload
    def __getitem__(self, index: slice, /) -> Sequence[Match]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Match]: ...
    def __bool__(self) -> bool: ...

class ScanSpace:
    def scan(
        self,
        value: Pattern | Sequence[Pattern],
        /,
        *,
        before: int = 0,
        after: int = 0,
        maximum_matches: int | None = None,
    ) -> MatchSet: ...

class PatternFactory:
    def bytes(self, value: builtins.bytes, /, *, id: LiteralString | None = None) -> Pattern: ...
    def text(
        self,
        value: str,
        /,
        *,
        encoding: PatternEncoding = "utf-8",
        case: PatternCase = "sensitive",
        id: LiteralString | None = None,
    ) -> Pattern: ...
    def masked(self, value: LiteralString, /, *, id: LiteralString | None = None) -> Pattern: ...
    def regex(
        self,
        value: LiteralString,
        /,
        *,
        dialect: Literal["re2"] = "re2",
        encoding: PatternEncoding = "utf-8",
        case: PatternCase = "sensitive",
        id: LiteralString | None = None,
    ) -> Pattern: ...

pattern: Final[PatternFactory]

class EventEnvelope[T]:
    event_id: str
    event_schema_id: str
    schema_hash: str
    tenant_id: str
    peer_id: str | None
    subject: SubjectKey[Any] | None
    producer_timestamp: datetime | None
    ingest_timestamp: datetime
    ingest_cursor: int
    source_sequence: int | None
    source_generation: int | None
    executable_id: str | None
    payload: T

class ObservationEvent[T](EventEnvelope[T]): ...
class RemovalEvent[T](EventEnvelope[T]): ...
class MatchEvent(EventEnvelope[WireRecord]): ...
class FaultEvent(EventEnvelope[WireRecord]): ...
class ActionDeliveryEvent[T](EventEnvelope[T]): ...
class CaptureResultEvent[T](EventEnvelope[T]): ...

class HistoryError(RuntimeError): ...
class HistoryUnavailable(HistoryError): ...
class HistoryLimitExceeded(HistoryError): ...

class HistoryQuery[T](AsyncIterator[T]):
    def tenant(self, tenant_id: str, /) -> Self: ...
    def peer(self, peer_id: str, /) -> Self: ...
    def between(self, start: datetime, end: datetime, /) -> Self: ...
    def where(self, predicate: Callable[[T], bool], /) -> Self: ...
    def limit(self, count: int, /) -> Self: ...
    def order_by(self, timestamp: Literal["ingest", "producer"], /) -> Self: ...
    async def collect(self) -> tuple[T, ...]: ...
    async def count(self) -> int: ...
    async def exists(self) -> bool: ...
    def __aiter__(self) -> Self: ...
    async def __anext__(self) -> T: ...

class History:
    def events[T](self, event_type: type[T], /) -> HistoryQuery[EventEnvelope[T]]: ...

class FleetHistory(History): ...

class StateScope(StrEnum):
    SESSION = "session"
    PEER = "peer"
    SUBJECT = "subject"
    CORRELATION_GROUP = "correlation_group"
    SHARED = "shared"

class StateKey[T]:
    def __init__(
        self,
        id: LiteralString,
        value_type: type[T],
        /,
        *,
        scope: StateScope,
        default: T | None = None,
        classification: Literal["public", "internal", "sensitive", "secret"] = "internal",
    ) -> None: ...

class State:
    def get[T](self, key: StateKey[T], /, *, identity: CanonicalKey | None = None) -> T | None: ...
    def require[T](self, key: StateKey[T], /, *, identity: CanonicalKey | None = None) -> T: ...
    def set[T](self, key: StateKey[T], value: T, /, *, identity: CanonicalKey | None = None) -> None: ...
    def delete[T](self, key: StateKey[T], /, *, identity: CanonicalKey | None = None) -> None: ...
    def compare_and_set[T](
        self,
        key: StateKey[T],
        expected: T | None,
        value: T,
        /,
        *,
        identity: CanonicalKey | None = None,
    ) -> bool: ...

class SharedState(State): ...

class _MigrationDecorator(Protocol):
    def __call__[T, U](self, target: Callable[[T], U], /) -> Callable[[T], U]: ...

def state_migration(*, from_schema: LiteralString, to: StateKey[Any]) -> _MigrationDecorator: ...

class Transaction(AbstractContextManager[Transaction]):
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool | None: ...

def transaction() -> Transaction: ...

class PostDisposition(StrEnum):
    QUEUED = "queued"
    DRY_RUN = "dry_run"
    SUPPRESSED = "suppressed"

class PostReceipt[T]:
    intent_id: str
    disposition: PostDisposition
    sink_id: str
    schema_id: str
    policy_version: str

class PostSink[RequestT, AckT](Protocol):
    def __call__(self, request: RequestT, /) -> PostReceipt[AckT]: ...

class PostCapabilities: ...

class EventReceipt:
    intent_id: str
    schema_id: str

class Telemetry:
    def emit(self, record: EventRecord, /) -> EventReceipt: ...

class RetentionReceipt:
    intent_id: str

class RetainReads(AbstractContextManager[RetainReads]):
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool | None: ...

class Retention:
    def retain(self, value: object, /, *, ttl: timedelta | None = None) -> RetentionReceipt: ...
    def retain_reads(self, *, ttl: timedelta | None = None) -> RetainReads: ...

class CaptureReceipt:
    intent_id: str
    profile_id: str

class PeerCapture[**P](Protocol):
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> CaptureReceipt: ...

class TraceScope(AbstractContextManager[TraceScope]):
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool | None: ...

class Trace:
    def __call__(self, *values: object, label: LiteralString | None = None) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def scope(self, *, enabled: bool = True) -> TraceScope: ...

telemetry: Final[Telemetry]
retention: Final[Retention]
trace: Final[Trace]

class ServiceError(RuntimeError): ...
class ServiceUnavailable(ServiceError): ...
class ServiceTimedOut(ServiceError): ...
class ServiceCanceled(ServiceError): ...
class ServiceRejected(ServiceError): ...
class ServiceMalformed(ServiceError): ...

class Service: ...

class ServiceCall[T](Awaitable[T]):
    def __await__(self) -> Generator[Any, Any, T]: ...

class ServiceMethod[RequestT, ResponseT](Protocol):
    def __call__(self, request: RequestT, /) -> ServiceCall[ResponseT]: ...

class TaskGroupExit(StrEnum):
    CANCEL_PENDING = "cancel_pending"
    WAIT_PENDING = "wait_pending"

class TaskHandle[T](Awaitable[T]):
    @property
    def done(self) -> bool: ...
    def cancel(self) -> None: ...
    def result(self) -> T: ...
    def __await__(self) -> Generator[Any, Any, T]: ...

class TaskGroup(AbstractAsyncContextManager[TaskGroup]):
    def __init__(self, *, on_exit: TaskGroupExit = ...) -> None: ...
    def start[T](self, call: ServiceCall[T], /) -> TaskHandle[T]: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type: object, exc_value: object, traceback: object) -> bool | None: ...

class FaultedRule(RuntimeError): ...
class SoftBudgetExceeded(RuntimeError): ...

class FaultKind(StrEnum):
    PYTHON_EXCEPTION = "python_exception"
    ENGINE_EXCEPTION = "engine_exception"
    CONTROL_FAULT = "control_fault"
    INTEGRITY_FAULT = "integrity_fault"

class Fault:
    kind: FaultKind
    code: str
    message: str
    source_module: str | None
    source_line: int | None

class FaultChain(Sequence[Fault]):
    @overload
    def __getitem__(self, index: int, /) -> Fault: ...
    @overload
    def __getitem__(self, index: slice, /) -> Sequence[Fault]: ...
    def __len__(self) -> int: ...

class FaultContext:
    chain: FaultChain
    execution_id: str
    invocation_id: str
    attempt: int

class FinalizerContext:
    candidate: bool
    execution_id: str
    invocation_id: str

class FaultDecision: ...
class RetryOnce(FaultDecision): ...
class Complete(FaultDecision):
    value: bool
class Abort(FaultDecision):
    reason: str
class Quarantine(FaultDecision):
    reason: str

class FinalizerDecision: ...
class Keep(FinalizerDecision): ...
class Replace(FinalizerDecision):
    value: bool
class FinalizerAbort(FinalizerDecision):
    reason: str

def retry_once() -> RetryOnce: ...
def complete(value: bool, /) -> Complete: ...
def abort(reason: str, /) -> Abort: ...
def quarantine(reason: str, /) -> Quarantine: ...
def keep() -> Keep: ...
def replace(value: bool, /) -> Replace: ...
def finalizer_abort(reason: str, /) -> FinalizerAbort: ...

class _DeclarationDecorator(Protocol):
    def __call__[F: Callable[..., object]](self, target: F, /) -> F: ...

def on_fault(entrypoint: object | None = None, /) -> _DeclarationDecorator: ...
def on_double_fault(target: Callable[..., FaultDecision] | Callable[..., Awaitable[FaultDecision]] | None = None, /) -> _DeclarationDecorator: ...
def finalizer(entrypoint: object | None = None, /) -> _DeclarationDecorator: ...
