if(NOT DEFINED RULE_ENGINE_RUNTIME_ROOT OR RULE_ENGINE_RUNTIME_ROOT STREQUAL "")
    message(FATAL_ERROR "RULE_ENGINE_RUNTIME_ROOT is required")
endif()
if(NOT DEFINED RULE_ENGINE_EXPECTED_RUNTIME_MANIFEST OR
   RULE_ENGINE_EXPECTED_RUNTIME_MANIFEST STREQUAL "")
    message(FATAL_ERROR "RULE_ENGINE_EXPECTED_RUNTIME_MANIFEST is required")
endif()

cmake_path(ABSOLUTE_PATH RULE_ENGINE_RUNTIME_ROOT NORMALIZE OUTPUT_VARIABLE runtime_root)
cmake_path(
    ABSOLUTE_PATH RULE_ENGINE_EXPECTED_RUNTIME_MANIFEST
    NORMALIZE
    OUTPUT_VARIABLE expected_manifest_path
)
if(NOT IS_DIRECTORY "${runtime_root}")
    message(FATAL_ERROR "Exact private runtime root is absent: ${runtime_root}")
endif()
if(NOT EXISTS "${expected_manifest_path}" OR IS_DIRECTORY "${expected_manifest_path}")
    message(FATAL_ERROR "Pinned private runtime manifest is absent: ${expected_manifest_path}")
endif()

set(actual_manifest_path "${runtime_root}/rule-engine-python-runtime.manifest")
if(NOT EXISTS "${actual_manifest_path}" OR IS_DIRECTORY "${actual_manifest_path}" OR
   IS_SYMLINK "${actual_manifest_path}")
    message(FATAL_ERROR "Staged runtime has no regular installation manifest")
endif()
file(READ "${expected_manifest_path}" expected_manifest)
file(READ "${actual_manifest_path}" actual_manifest)
if(NOT actual_manifest STREQUAL expected_manifest)
    message(FATAL_ERROR "Staged runtime manifest is not the exact pinned CPython 3.14.6 manifest")
endif()

string(REPLACE "\r\n" "\n" expected_manifest "${expected_manifest}")
string(REPLACE "\n" ";" manifest_lines "${expected_manifest}")
set(expected_names rule-engine-python-runtime.manifest)
set(expected_worker_sha256 "")
foreach(line IN LISTS manifest_lines)
    if(line STREQUAL "")
        continue()
    endif()
    if(line MATCHES "^format=1$" OR
       line MATCHES "^python_version=3\\.14\\.6$" OR
       line MATCHES "^artifact_sha256=df901e84a896ff1ee720ad03377e0c8d8c2244fda79808aeeaff6316df1cb75c$" OR
       line MATCHES "^worker_protocol=1$" OR
       line MATCHES "^worker_script=rule_engine_python_worker\\.py$")
        continue()
    endif()
    if(line MATCHES "^worker_script_sha256=([0-9a-f]+)$")
        set(candidate_worker_sha256 "${CMAKE_MATCH_1}")
        string(LENGTH "${candidate_worker_sha256}" candidate_worker_sha256_length)
        if(NOT candidate_worker_sha256_length EQUAL 64)
            message(FATAL_ERROR "Pinned runtime worker digest does not contain 64 hexadecimal characters")
        endif()
        set(expected_worker_sha256 "${candidate_worker_sha256}")
        continue()
    endif()
    if(NOT line MATCHES "^file\t([^\t/\\\\]+)\t([0-9]+)\t([0-9a-f]+)$")
        message(FATAL_ERROR "Pinned runtime manifest contains an invalid line: ${line}")
    endif()
    set(filename "${CMAKE_MATCH_1}")
    set(expected_size "${CMAKE_MATCH_2}")
    set(expected_sha256 "${CMAKE_MATCH_3}")
    string(LENGTH "${expected_sha256}" expected_sha256_length)
    if(NOT expected_sha256_length EQUAL 64)
        message(FATAL_ERROR "Pinned runtime file digest is not 64 hexadecimal characters: ${filename}")
    endif()
    set(path "${runtime_root}/${filename}")
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}" OR IS_SYMLINK "${path}")
        message(FATAL_ERROR "Private runtime file is absent or not regular: ${filename}")
    endif()
    file(SIZE "${path}" actual_size)
    if(NOT actual_size EQUAL expected_size)
        message(FATAL_ERROR "Private runtime file size mismatch: ${filename}")
    endif()
    file(SHA256 "${path}" actual_sha256)
    if(NOT actual_sha256 STREQUAL expected_sha256)
        message(FATAL_ERROR "Private runtime SHA-256 mismatch: ${filename}")
    endif()
    list(APPEND expected_names "${filename}")
endforeach()

if(expected_worker_sha256 STREQUAL "")
    message(FATAL_ERROR "Pinned runtime manifest has no worker script digest")
endif()
set(worker_path "${runtime_root}/rule_engine_python_worker.py")
if(NOT EXISTS "${worker_path}" OR IS_DIRECTORY "${worker_path}" OR IS_SYMLINK "${worker_path}")
    message(FATAL_ERROR "Private runtime worker script is absent or not regular")
endif()
file(SHA256 "${worker_path}" actual_worker_sha256)
if(NOT actual_worker_sha256 STREQUAL expected_worker_sha256)
    message(FATAL_ERROR "Private runtime worker script SHA-256 mismatch")
endif()
list(APPEND expected_names rule_engine_python_worker.py)

file(GLOB actual_entries RELATIVE "${runtime_root}" "${runtime_root}/*")
list(SORT actual_entries)
list(SORT expected_names)
if(NOT actual_entries STREQUAL expected_names)
    message(FATAL_ERROR "Private runtime contains missing or unexpected entries")
endif()

message(STATUS "Validated exact private CPython 3.14.6 runtime: ${runtime_root}")
